# Generated by Django 5.0.1 on 2024-02-18 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclass',
            options={'verbose_name_plural': 'Student Class'},
        ),
        migrations.AlterField(
            model_name='tution',
            name='Student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuitions.studentclass'),
        ),
    ]
