# Generated by Django 5.0.1 on 2024-02-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0003_tuition_delete_tution'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='tutor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutors.tutoraccount'),
        ),
    ]
